"""Safe Tcl helpers for Vivado batch scripts.

User-provided values are validated and brace-quoted. Values that cannot be
safely embedded in Tcl are rejected rather than interpolated into a shell
command.
"""

from __future__ import annotations

import re
from pathlib import Path

from vivado_mcp.errors import InvalidPartError, InvalidProjectPathError

# Vivado project names are identifiers (letters, digits, underscore).
_PROJECT_NAME_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# FPGA part strings like xc7a35tcpg236-1 or xcvu9p-flgb2104-2-i
_PART_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._+-]*$")


def tcl_quote(value: str) -> str:
    """Quote a string for safe inclusion in a Tcl script using braces.

    Raises:
        InvalidProjectPathError: If the value contains characters that break
            Tcl brace quoting (notably ``}``) or embedded nulls.
    """
    if "\x00" in value:
        raise InvalidProjectPathError("Value contains a null byte.")
    if "}" in value:
        raise InvalidProjectPathError(
            "Value contains '}' which cannot be safely brace-quoted in Tcl."
        )
    return "{" + value + "}"


def validate_project_name(name: str) -> str:
    """Validate and return a Vivado project name."""
    cleaned = name.strip()
    if not cleaned:
        raise InvalidProjectPathError("Project name must not be empty.")
    if not _PROJECT_NAME_PATTERN.fullmatch(cleaned):
        raise InvalidProjectPathError(
            "Project name must start with a letter or underscore and contain "
            "only letters, digits, and underscores."
        )
    return cleaned


def validate_part(part: str) -> str:
    """Validate and return a Vivado FPGA part string."""
    cleaned = part.strip()
    if not cleaned:
        raise InvalidPartError("FPGA part string must not be empty.")
    if not _PART_PATTERN.fullmatch(cleaned):
        raise InvalidPartError(
            f"Invalid Vivado part string: {part!r}. "
            "Expected a part id such as 'xc7a35tcpg236-1'."
        )
    if "}" in cleaned or "{" in cleaned:
        raise InvalidPartError(f"Invalid Vivado part string: {part!r}.")
    return cleaned


def normalize_user_path(path: str | Path) -> Path:
    """Expand and normalize a user-supplied filesystem path."""
    if isinstance(path, Path):
        text = str(path)
    else:
        text = path
    if not text or not str(text).strip():
        raise InvalidProjectPathError("Path must not be empty.")
    if "\x00" in text:
        raise InvalidProjectPathError("Path contains a null byte.")
    cleaned = Path(text.strip()).expanduser()
    # Resolve relative segments without requiring the path to exist.
    return cleaned


def build_create_project_tcl(*, name: str, parent_dir: Path, part: str) -> str:
    """Build Tcl that creates a project then exits batch mode cleanly."""
    name_q = tcl_quote(name)
    parent_q = tcl_quote(_tcl_path(parent_dir))
    part_q = tcl_quote(part)
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"create_project {name_q} {parent_q} -part {part_q}",
            "puts \"VIVADO_MCP_STATUS=OK\"",
            "puts \"VIVADO_MCP_PROJECT_NAME=[current_project]\"",
            "puts \"VIVADO_MCP_PROJECT_DIR=[get_property DIRECTORY [current_project]]\"",
            "puts \"VIVADO_MCP_PROJECT_PART=[get_property PART [current_project]]\"",
            "close_project",
            "exit 0",
            "",
        ]
    )


def build_open_project_tcl(*, xpr_path: Path) -> str:
    """Build Tcl that opens a project, reports status, then closes and exits."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"open_project {xpr_q}",
            "puts \"VIVADO_MCP_STATUS=OK\"",
            "puts \"VIVADO_MCP_PROJECT_NAME=[current_project]\"",
            "puts \"VIVADO_MCP_PROJECT_DIR=[get_property DIRECTORY [current_project]]\"",
            "puts \"VIVADO_MCP_PROJECT_PART=[get_property PART [current_project]]\"",
            "close_project",
            "exit 0",
            "",
        ]
    )


def build_close_project_tcl(*, xpr_path: Path) -> str:
    """Build Tcl that opens then closes a project in batch mode."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"open_project {xpr_q}",
            "close_project",
            "puts \"VIVADO_MCP_STATUS=OK\"",
            "puts \"VIVADO_MCP_CLOSED=1\"",
            "exit 0",
            "",
        ]
    )


def _tcl_path(path: Path) -> str:
    """Return a path string suitable for Tcl on Windows and Linux.

    Vivado on Windows accepts forward slashes. Always normalize separators so
    Windows-style paths remain safe even when this code runs on Linux (for
    example in CI while generating Tcl for a remote Windows Vivado).
    """
    return str(path.expanduser()).replace("\\", "/")
