"""Safe Tcl helpers for Vivado batch scripts.

User-provided values are validated and brace-quoted. Values that cannot be
safely embedded in Tcl are rejected rather than interpolated into a shell
command.
"""

from __future__ import annotations

import re
from pathlib import Path

from vivado_mcp.errors import (
    InvalidPartError,
    InvalidProjectPathError,
    InvalidSimulationTimeError,
    InvalidSourceError,
    InvalidTopModuleError,
)

# Vivado project names are identifiers (letters, digits, underscore).
_PROJECT_NAME_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# FPGA part strings like xc7a35tcpg236-1 or xcvu9p-flgb2104-2-i
_PART_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._+-]*$")

# Simulation runtime: 100ns, 1.5us, 10ms, etc. Rejects arbitrary Tcl.
_SIM_TIME_PATTERN = re.compile(
    r"^(?P<value>\d+(?:\.\d+)?)(?P<unit>fs|ps|ns|us|ms|s)$",
    re.IGNORECASE,
)

# HDL module identifiers
_TOP_MODULE_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_$]*$")

_ALLOWED_FILESETS = frozenset({"sources_1", "sim_1"})


def tcl_quote(value: str) -> str:
    """Quote a string for safe inclusion in a Tcl script using braces.

    Raises:
        InvalidProjectPathError: If the value contains characters that break
            Tcl brace quoting (notably ``}``) or embedded nulls.
    """
    if "\x00" in value:
        raise InvalidProjectPathError("Value contains a null byte.")
    if "}" in value:
        raise InvalidProjectPathError(
            "Value contains '}' which cannot be safely brace-quoted in Tcl."
        )
    return "{" + value + "}"


def validate_project_name(name: str) -> str:
    """Validate and return a Vivado project name."""
    cleaned = name.strip()
    if not cleaned:
        raise InvalidProjectPathError("Project name must not be empty.")
    if not _PROJECT_NAME_PATTERN.fullmatch(cleaned):
        raise InvalidProjectPathError(
            "Project name must start with a letter or underscore and contain "
            "only letters, digits, and underscores."
        )
    return cleaned


def validate_part(part: str) -> str:
    """Validate and return a Vivado FPGA part string."""
    cleaned = part.strip()
    if not cleaned:
        raise InvalidPartError("FPGA part string must not be empty.")
    if not _PART_PATTERN.fullmatch(cleaned):
        raise InvalidPartError(
            f"Invalid Vivado part string: {part!r}. "
            "Expected a part id such as 'xc7a35tcpg236-1'."
        )
    if "}" in cleaned or "{" in cleaned:
        raise InvalidPartError(f"Invalid Vivado part string: {part!r}.")
    return cleaned


def normalize_user_path(path: str | Path) -> Path:
    """Expand and normalize a user-supplied filesystem path."""
    if isinstance(path, Path):
        text = str(path)
    else:
        text = path
    if not text or not str(text).strip():
        raise InvalidProjectPathError("Path must not be empty.")
    if "\x00" in text:
        raise InvalidProjectPathError("Path contains a null byte.")
    cleaned = Path(text.strip()).expanduser()
    # Resolve relative segments without requiring the path to exist.
    return cleaned


def build_create_project_tcl(*, name: str, parent_dir: Path, part: str) -> str:
    """Build Tcl that creates a project then exits batch mode cleanly."""
    name_q = tcl_quote(name)
    parent_q = tcl_quote(_tcl_path(parent_dir))
    part_q = tcl_quote(part)
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"create_project {name_q} {parent_q} -part {part_q}",
            "puts \"VIVADO_MCP_STATUS=OK\"",
            "puts \"VIVADO_MCP_PROJECT_NAME=[current_project]\"",
            "puts \"VIVADO_MCP_PROJECT_DIR=[get_property DIRECTORY [current_project]]\"",
            "puts \"VIVADO_MCP_PROJECT_PART=[get_property PART [current_project]]\"",
            "close_project",
            "exit 0",
            "",
        ]
    )


def build_open_project_tcl(*, xpr_path: Path) -> str:
    """Build Tcl that opens a project, reports status, then closes and exits."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            *_tcl_open_project_with_lock_retry(xpr_q),
            "puts \"VIVADO_MCP_STATUS=OK\"",
            "puts \"VIVADO_MCP_PROJECT_NAME=[current_project]\"",
            "puts \"VIVADO_MCP_PROJECT_DIR=[get_property DIRECTORY [current_project]]\"",
            "puts \"VIVADO_MCP_PROJECT_PART=[get_property PART [current_project]]\"",
            "close_project",
            "exit 0",
            "",
        ]
    )


def build_close_project_tcl(*, xpr_path: Path) -> str:
    """Build Tcl that opens then closes a project in batch mode.

    Retries once after clearing a stale ``.lck`` file. This is important on
    Windows where a previous batch Vivado process can leave a lock behind.
    """
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            *_tcl_open_project_with_lock_retry(xpr_q),
            "close_project",
            "puts \"VIVADO_MCP_STATUS=OK\"",
            "puts \"VIVADO_MCP_CLOSED=1\"",
            "exit 0",
            "",
        ]
    )


def validate_fileset(fileset: str) -> str:
    """Validate a Vivado fileset name (allowlisted)."""
    cleaned = fileset.strip()
    if cleaned not in _ALLOWED_FILESETS:
        raise InvalidSourceError(
            f"Unsupported fileset {fileset!r}. Use 'sources_1' or 'sim_1'."
        )
    return cleaned


def validate_simulation_time(simulation_time: str) -> str:
    """Validate and normalize a Vivado simulation runtime string.

    Accepts values such as ``10ns``, ``100ns``, ``1us``, ``1ms``. Rejects
    arbitrary Tcl expressions.
    """
    cleaned = simulation_time.strip()
    if not cleaned:
        raise InvalidSimulationTimeError("simulation_time must not be empty.")
    if any(ch in cleaned for ch in " ;${}[]\\\"'`|&<>"):
        raise InvalidSimulationTimeError(
            f"Invalid simulation_time {simulation_time!r}: "
            "special characters and Tcl expressions are not allowed."
        )
    match = _SIM_TIME_PATTERN.fullmatch(cleaned)
    if not match:
        raise InvalidSimulationTimeError(
            f"Invalid simulation_time {simulation_time!r}. "
            "Use a value like '100ns', '1us', or '1ms'."
        )
    return f"{match.group('value')}{match.group('unit').lower()}"


def validate_top_module(top_module: str) -> str:
    """Validate a simulation top module identifier."""
    cleaned = top_module.strip()
    if not cleaned:
        raise InvalidTopModuleError("top_module must not be empty.")
    if not _TOP_MODULE_PATTERN.fullmatch(cleaned):
        raise InvalidTopModuleError(
            f"Invalid top_module {top_module!r}. "
            "Use a Verilog/SystemVerilog identifier."
        )
    if "}" in cleaned or "{" in cleaned:
        raise InvalidTopModuleError(f"Invalid top_module {top_module!r}.")
    return cleaned


def build_add_source_tcl(
    *,
    xpr_path: Path,
    source_path: Path,
    fileset: str = "sources_1",
) -> str:
    """Build Tcl that adds a source file to ``sources_1`` or ``sim_1``."""
    fileset_name = validate_fileset(fileset)
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    source_q = tcl_quote(_tcl_path(source_path))
    lines = [
        "# Generated by vivado-mcp — do not edit",
        *_tcl_open_project_with_lock_retry(xpr_q),
    ]
    if fileset_name == "sim_1":
        lines.extend(
            [
                'if {[llength [get_filesets -quiet sim_1]] == 0} {',
                "create_fileset -simset sim_1",
                "}",
                f"add_files -fileset sim_1 -norecurse {source_q}",
                "update_compile_order -fileset sim_1",
            ]
        )
    else:
        lines.extend(
            [
                f"add_files -norecurse {source_q}",
                "update_compile_order -fileset sources_1",
                # Ensure a design top is set so synthesis/implementation can run.
                "set _mcp_top [get_property top [current_fileset]]",
                'if {$_mcp_top eq ""} {',
                f"set_property top {tcl_quote(Path(source_path).stem)} [current_fileset]",
                "set_property top_lib xil_defaultlib [current_fileset]",
                "update_compile_order -fileset sources_1",
                "}",
            ]
        )
    lines.extend(
        [
            "puts \"VIVADO_MCP_STATUS=OK\"",
            f"puts \"VIVADO_MCP_SOURCE={_tcl_path(source_path)}\"",
            f"puts \"VIVADO_MCP_FILESET={fileset_name}\"",
            "close_project",
            "exit 0",
            "",
        ]
    )
    return "\n".join(lines)


def build_run_simulation_tcl(
    *,
    xpr_path: Path,
    simulation_time: str,
    top_module: str | None = None,
) -> str:
    """Build Tcl for RTL behavioral simulation with XSim (Vivado 2018.2+).

    Opens the project, ensures ``sim_1`` has sources, optionally sets the
    simulation top, configures runtime, launches behavioral simulation, then
    closes cleanly. Never opens the GUI.
    """
    sim_time = validate_simulation_time(simulation_time)
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    time_q = tcl_quote(sim_time)
    lines = [
        "# Generated by vivado-mcp — do not edit",
        f"open_project {xpr_q}",
        "set_property target_simulator XSim [current_project]",
        'if {[llength [get_filesets -quiet sim_1]] == 0} {',
        "create_fileset -simset sim_1",
        "}",
        "set _mcp_sim_files [get_files -quiet -of_objects [get_filesets sim_1]]",
        'if {[llength $_mcp_sim_files] == 0} {',
        'puts "VIVADO_MCP_STATUS=ERROR"',
        'puts "VIVADO_MCP_SIM_STATUS=no_sources"',
        'puts "VIVADO_MCP_SIM_ERROR=No simulation sources in fileset sim_1"',
        "close_project",
        "exit 1",
        "}",
        "update_compile_order -fileset sources_1",
        "update_compile_order -fileset sim_1",
    ]
    if top_module is not None:
        top = validate_top_module(top_module)
        top_q = tcl_quote(top)
        lines.extend(
            [
                f"set_property top {top_q} [get_filesets sim_1]",
                "set_property top_lib xil_defaultlib [get_filesets sim_1]",
            ]
        )
    lines.extend(
        [
            'set _mcp_top [get_property top [get_filesets sim_1]]',
            'if {$_mcp_top eq ""} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SIM_STATUS=failed"',
            'puts "VIVADO_MCP_SIM_ERROR=Simulation top module is not set"',
            "close_project",
            "exit 1",
            "}",
            f"set_property -name {{xsim.simulate.runtime}} -value {time_q} "
            "-objects [get_filesets sim_1]",
            'puts "VIVADO_MCP_SIM_TOP=$_mcp_top"',
            f'puts "VIVADO_MCP_SIM_TIME={sim_time}"',
            "if {[catch {launch_simulation -mode behavioral} _mcp_launch_err]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SIM_STATUS=failed"',
            'puts "VIVADO_MCP_SIM_ERROR=$_mcp_launch_err"',
            "catch {close_sim -quiet}",
            "close_project",
            "exit 1",
            "}",
            # Runtime is configured via xsim.simulate.runtime; run again if needed.
            f"catch {{run {sim_time}}}",
            "catch {close_sim -quiet}",
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            'puts "VIVADO_MCP_SIM_STATUS=passed"',
            "exit 0",
            "",
        ]
    )
    return "\n".join(lines)


def build_remove_source_tcl(*, xpr_path: Path, source_path: Path) -> str:
    """Build Tcl that removes a source from the project (keeps the file)."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    source_q = tcl_quote(_tcl_path(source_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"open_project {xpr_q}",
            f"set _mcp_files [get_files -quiet {source_q}]",
            'if {$_mcp_files eq ""} {',
            "puts \"VIVADO_MCP_STATUS=ERROR\"",
            "puts \"VIVADO_MCP_ERROR=SOURCE_NOT_IN_PROJECT\"",
            "close_project",
            "exit 1",
            "}",
            "remove_files $_mcp_files",
            "update_compile_order -fileset sources_1",
            "puts \"VIVADO_MCP_STATUS=OK\"",
            f"puts \"VIVADO_MCP_SOURCE={_tcl_path(source_path)}\"",
            "puts \"VIVADO_MCP_REMOVED=1\"",
            "close_project",
            "exit 0",
            "",
        ]
    )


def build_list_sources_tcl(*, xpr_path: Path) -> str:
    """Build Tcl that lists design sources with type and library."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"open_project {xpr_q}",
            "foreach _mcp_f [get_files -of_objects [get_filesets sources_1]] {",
            "puts \"VIVADO_MCP_SOURCE_PATH=[file normalize $_mcp_f]\"",
            "puts \"VIVADO_MCP_SOURCE_TYPE=[get_property FILE_TYPE $_mcp_f]\"",
            "puts \"VIVADO_MCP_SOURCE_LIBRARY=[get_property LIBRARY $_mcp_f]\"",
            "puts \"VIVADO_MCP_SOURCE_END=1\"",
            "}",
            "puts \"VIVADO_MCP_STATUS=OK\"",
            "close_project",
            "exit 0",
            "",
        ]
    )


def build_run_synthesis_tcl(
    *,
    xpr_path: Path,
    report_dir: Path,
) -> str:
    """Build Tcl for synthesis + utilization/timing reports (Vivado 2018.2+).

    Opens the project, verifies sources and top, ensures ``synth_1``, launches
    synthesis, waits, then writes utilization and timing-summary reports.
    Never opens the GUI.
    """
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    report_dir_q = tcl_quote(_tcl_path(report_dir))
    util_path = report_dir / "utilization.rpt"
    timing_path = report_dir / "timing_summary.rpt"
    util_q = tcl_quote(_tcl_path(util_path))
    timing_q = tcl_quote(_tcl_path(timing_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            *_tcl_open_project_with_lock_retry(xpr_q),
            "set_property source_mgmt_mode All [current_project]",
            "update_compile_order -fileset sources_1",
            "set _mcp_src [get_files -quiet -of_objects [get_filesets sources_1]]",
            "if {[llength $_mcp_src] == 0} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=failed"',
            'puts "VIVADO_MCP_SYNTH_ERROR=No design sources in fileset sources_1"',
            "close_project",
            "exit 1",
            "}",
            "set _mcp_top [get_property top [current_fileset]]",
            'if {$_mcp_top eq ""} {',
            # Auto-select a top when Vivado did not infer one (common after
            # rapid batch create/add sequences on Windows).
            "set _mcp_candidates [get_files -quiet -of_objects [get_filesets sources_1]]",
            "if {[llength $_mcp_candidates] > 0} {",
            "set _mcp_guess [file rootname [file tail [lindex $_mcp_candidates 0]]]",
            "set_property top $_mcp_guess [current_fileset]",
            "set_property top_lib xil_defaultlib [current_fileset]",
            "update_compile_order -fileset sources_1",
            "set _mcp_top [get_property top [current_fileset]]",
            "}",
            "}",
            'if {$_mcp_top eq ""} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=failed"',
            'puts "VIVADO_MCP_SYNTH_ERROR=Top module is not set on sources_1"',
            "close_project",
            "exit 1",
            "}",
            'puts "VIVADO_MCP_SYNTH_TOP=$_mcp_top"',
            "if {[llength [get_runs -quiet synth_1]] == 0} {",
            "if {[catch {create_run synth_1} _mcp_cr_err]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=failed"',
            'puts "VIVADO_MCP_SYNTH_ERROR=Could not create synth_1 run: $_mcp_cr_err"',
            "close_project",
            "exit 1",
            "}",
            "}",
            "catch {reset_run synth_1}",
            "if {[catch {launch_runs synth_1 -jobs 1} _mcp_launch_err]} {",
            "if {[catch {launch_runs synth_1} _mcp_launch_err2]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=failed"',
            'puts "VIVADO_MCP_SYNTH_ERROR=$_mcp_launch_err2"',
            "close_project",
            "exit 1",
            "}",
            "}",
            "wait_on_run synth_1",
            "set _mcp_run_status [get_property STATUS [get_runs synth_1]]",
            "set _mcp_progress [get_property PROGRESS [get_runs synth_1]]",
            'puts "VIVADO_MCP_SYNTH_RUN_STATUS=$_mcp_run_status"',
            'puts "VIVADO_MCP_SYNTH_PROGRESS=$_mcp_progress"',
            'if {![string match -nocase "*Complete*" $_mcp_run_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=failed"',
            'puts "VIVADO_MCP_SYNTH_ERROR=Synthesis run did not complete: $_mcp_run_status"',
            "close_project",
            "exit 1",
            "}",
            f"file mkdir {report_dir_q}",
            "if {[catch {open_run synth_1 -name mcp_synth_netlist} _mcp_open_err]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=failed"',
            'puts "VIVADO_MCP_SYNTH_ERROR=Could not open synth_1 run: $_mcp_open_err"',
            "close_project",
            "exit 1",
            "}",
            f"report_utilization -file {util_q}",
            f'puts "VIVADO_MCP_UTIL_REPORT={_tcl_path(util_path)}"',
            "if {[catch {"
            f"report_timing_summary -delay_type min_max -max_paths 10 -file {timing_q}"
            "} _mcp_tm_err]} {",
            'puts "VIVADO_MCP_TIMING_STATUS=not_available"',
            'puts "VIVADO_MCP_TIMING_ERROR=$_mcp_tm_err"',
            "} else {",
            'puts "VIVADO_MCP_TIMING_STATUS=available"',
            f'puts "VIVADO_MCP_TIMING_REPORT={_tcl_path(timing_path)}"',
            "}",
            "catch {close_design}",
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            'puts "VIVADO_MCP_SYNTH_STATUS=completed"',
            "exit 0",
            "",
        ]
    )


def build_report_utilization_tcl(
    *,
    xpr_path: Path,
    report_path: Path,
) -> str:
    """Build Tcl that regenerates a utilization report from ``synth_1``."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    report_dir_q = tcl_quote(_tcl_path(report_path.parent))
    report_q = tcl_quote(_tcl_path(report_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"open_project {xpr_q}",
            "if {[llength [get_runs -quiet synth_1]] == 0} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=not_started"',
            'puts "VIVADO_MCP_SYNTH_ERROR=synth_1 run does not exist"',
            "close_project",
            "exit 1",
            "}",
            "set _mcp_run_status [get_property STATUS [get_runs synth_1]]",
            'puts "VIVADO_MCP_SYNTH_RUN_STATUS=$_mcp_run_status"',
            'if {![string match -nocase "*Complete*" $_mcp_run_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=not_started"',
            'puts "VIVADO_MCP_SYNTH_ERROR=Synthesis has not completed: $_mcp_run_status"',
            "close_project",
            "exit 1",
            "}",
            f"file mkdir {report_dir_q}",
            "open_run synth_1 -name mcp_synth_netlist",
            f"report_utilization -file {report_q}",
            f'puts "VIVADO_MCP_UTIL_REPORT={_tcl_path(report_path)}"',
            "catch {close_design}",
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            "exit 0",
            "",
        ]
    )


def build_report_timing_tcl(
    *,
    xpr_path: Path,
    report_path: Path,
) -> str:
    """Build Tcl that regenerates a post-synthesis timing summary report."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    report_dir_q = tcl_quote(_tcl_path(report_path.parent))
    report_q = tcl_quote(_tcl_path(report_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"open_project {xpr_q}",
            "if {[llength [get_runs -quiet synth_1]] == 0} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=not_started"',
            'puts "VIVADO_MCP_SYNTH_ERROR=synth_1 run does not exist"',
            "close_project",
            "exit 1",
            "}",
            "set _mcp_run_status [get_property STATUS [get_runs synth_1]]",
            'puts "VIVADO_MCP_SYNTH_RUN_STATUS=$_mcp_run_status"',
            'if {![string match -nocase "*Complete*" $_mcp_run_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_SYNTH_STATUS=not_started"',
            'puts "VIVADO_MCP_SYNTH_ERROR=Synthesis has not completed: $_mcp_run_status"',
            "close_project",
            "exit 1",
            "}",
            f"file mkdir {report_dir_q}",
            "open_run synth_1 -name mcp_synth_netlist",
            "if {[catch {"
            f"report_timing_summary -delay_type min_max -max_paths 10 -file {report_q}"
            "} _mcp_tm_err]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_TIMING_STATUS=not_available"',
            'puts "VIVADO_MCP_TIMING_ERROR=$_mcp_tm_err"',
            "catch {close_design}",
            "close_project",
            "exit 1",
            "}",
            f'puts "VIVADO_MCP_TIMING_REPORT={_tcl_path(report_path)}"',
            'puts "VIVADO_MCP_TIMING_STATUS=available"',
            "catch {close_design}",
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            "exit 0",
            "",
        ]
    )


def build_run_implementation_tcl(
    *,
    xpr_path: Path,
    report_dir: Path,
) -> str:
    """Build Tcl for implementation + post-route reports (Vivado 2018.2+).

    Requires ``synth_1`` to have completed. Ensures ``impl_1``, launches it,
    waits, then writes implementation utilization and timing-summary reports.
    Never opens the GUI.
    """
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    report_dir_q = tcl_quote(_tcl_path(report_dir))
    util_path = report_dir / "impl_utilization.rpt"
    timing_path = report_dir / "impl_timing_summary.rpt"
    util_q = tcl_quote(_tcl_path(util_path))
    timing_q = tcl_quote(_tcl_path(timing_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            *_tcl_open_project_with_lock_retry(xpr_q),
            "set_property source_mgmt_mode All [current_project]",
            "update_compile_order -fileset sources_1",
            "set _mcp_top [get_property top [current_fileset]]",
            'if {$_mcp_top eq ""} {',
            "set _mcp_candidates [get_files -quiet -of_objects [get_filesets sources_1]]",
            "if {[llength $_mcp_candidates] > 0} {",
            "set _mcp_guess [file rootname [file tail [lindex $_mcp_candidates 0]]]",
            "set_property top $_mcp_guess [current_fileset]",
            "set_property top_lib xil_defaultlib [current_fileset]",
            "update_compile_order -fileset sources_1",
            "set _mcp_top [get_property top [current_fileset]]",
            "}",
            "}",
            'if {$_mcp_top eq ""} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=failed"',
            'puts "VIVADO_MCP_IMPL_ERROR=Top module is not set on sources_1"',
            "close_project",
            "exit 1",
            "}",
            'puts "VIVADO_MCP_IMPL_TOP=$_mcp_top"',
            "if {[llength [get_runs -quiet synth_1]] == 0} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=blocked"',
            'puts "VIVADO_MCP_IMPL_ERROR=Synthesis must complete before implementation"',
            "close_project",
            # Exit 0 so callers receive structured blocked status without a
            # process-level failure (helps avoid stale Windows .lck files).
            "exit 0",
            "}",
            "set _mcp_synth_status [get_property STATUS [get_runs synth_1]]",
            'puts "VIVADO_MCP_SYNTH_RUN_STATUS=$_mcp_synth_status"',
            'if {![string match -nocase "*Complete*" $_mcp_synth_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=blocked"',
            'puts "VIVADO_MCP_IMPL_ERROR=Synthesis must complete before implementation"',
            "close_project",
            "exit 0",
            "}",
            "if {[llength [get_runs -quiet impl_1]] == 0} {",
            "if {[catch {create_run impl_1 -parent_run synth_1} _mcp_cr_err]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=failed"',
            'puts "VIVADO_MCP_IMPL_ERROR=Could not create impl_1 run: $_mcp_cr_err"',
            "close_project",
            "exit 1",
            "}",
            "}",
            "catch {reset_run impl_1}",
            "if {[catch {launch_runs impl_1 -jobs 1} _mcp_launch_err]} {",
            "if {[catch {launch_runs impl_1} _mcp_launch_err2]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=failed"',
            'puts "VIVADO_MCP_IMPL_ERROR=$_mcp_launch_err2"',
            "close_project",
            "exit 1",
            "}",
            "}",
            "wait_on_run impl_1",
            "set _mcp_run_status [get_property STATUS [get_runs impl_1]]",
            "set _mcp_progress [get_property PROGRESS [get_runs impl_1]]",
            'puts "VIVADO_MCP_IMPL_RUN_STATUS=$_mcp_run_status"',
            'puts "VIVADO_MCP_IMPL_PROGRESS=$_mcp_progress"',
            'puts "VIVADO_MCP_IMPL_RUN=impl_1"',
            'if {![string match -nocase "*Complete*" $_mcp_run_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=failed"',
            'puts "VIVADO_MCP_IMPL_ERROR=Implementation run did not complete: $_mcp_run_status"',
            "close_project",
            "exit 1",
            "}",
            f"file mkdir {report_dir_q}",
            "if {[catch {open_run impl_1 -name mcp_impl_design} _mcp_open_err]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=failed"',
            'puts "VIVADO_MCP_IMPL_ERROR=Could not open impl_1 run: $_mcp_open_err"',
            "close_project",
            "exit 1",
            "}",
            f"report_utilization -file {util_q}",
            f'puts "VIVADO_MCP_IMPL_UTIL_REPORT={_tcl_path(util_path)}"',
            "if {[catch {"
            f"report_timing_summary -delay_type min_max -max_paths 10 -file {timing_q}"
            "} _mcp_tm_err]} {",
            'puts "VIVADO_MCP_TIMING_STATUS=not_available"',
            'puts "VIVADO_MCP_TIMING_ERROR=$_mcp_tm_err"',
            "} else {",
            'puts "VIVADO_MCP_TIMING_STATUS=available"',
            f'puts "VIVADO_MCP_IMPL_TIMING_REPORT={_tcl_path(timing_path)}"',
            "}",
            "catch {close_design}",
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            'puts "VIVADO_MCP_IMPL_STATUS=completed"',
            "exit 0",
            "",
        ]
    )


def build_impl_status_tcl(*, xpr_path: Path) -> str:
    """Build Tcl that reports ``impl_1`` / ``synth_1`` STATUS without launching."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            *_tcl_open_project_with_lock_retry(xpr_q),
            "if {[llength [get_runs -quiet synth_1]] == 0} {",
            'puts "VIVADO_MCP_SYNTH_STATUS=not_started"',
            "} else {",
            "set _mcp_synth_status [get_property STATUS [get_runs synth_1]]",
            'puts "VIVADO_MCP_SYNTH_RUN_STATUS=$_mcp_synth_status"',
            "}",
            "if {[llength [get_runs -quiet impl_1]] == 0} {",
            'puts "VIVADO_MCP_IMPL_STATUS=not_started"',
            'puts "VIVADO_MCP_IMPL_RUN_STATUS="',
            "} else {",
            "set _mcp_impl_status [get_property STATUS [get_runs impl_1]]",
            "set _mcp_progress [get_property PROGRESS [get_runs impl_1]]",
            'puts "VIVADO_MCP_IMPL_RUN=impl_1"',
            'puts "VIVADO_MCP_IMPL_RUN_STATUS=$_mcp_impl_status"',
            'puts "VIVADO_MCP_IMPL_PROGRESS=$_mcp_progress"',
            'puts "VIVADO_MCP_IMPL_STATUS=queried"',
            "}",
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            "exit 0",
            "",
        ]
    )


def build_report_impl_utilization_tcl(
    *,
    xpr_path: Path,
    report_path: Path,
) -> str:
    """Build Tcl that regenerates post-implementation utilization from ``impl_1``."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    report_dir_q = tcl_quote(_tcl_path(report_path.parent))
    report_q = tcl_quote(_tcl_path(report_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"open_project {xpr_q}",
            "if {[llength [get_runs -quiet impl_1]] == 0} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=not_started"',
            'puts "VIVADO_MCP_IMPL_ERROR=impl_1 run does not exist"',
            "close_project",
            "exit 1",
            "}",
            "set _mcp_run_status [get_property STATUS [get_runs impl_1]]",
            'puts "VIVADO_MCP_IMPL_RUN_STATUS=$_mcp_run_status"',
            'if {![string match -nocase "*Complete*" $_mcp_run_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=not_started"',
            'puts "VIVADO_MCP_IMPL_ERROR=Implementation has not completed: $_mcp_run_status"',
            "close_project",
            "exit 1",
            "}",
            f"file mkdir {report_dir_q}",
            "open_run impl_1 -name mcp_impl_design",
            f"report_utilization -file {report_q}",
            f'puts "VIVADO_MCP_IMPL_UTIL_REPORT={_tcl_path(report_path)}"',
            "catch {close_design}",
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            "exit 0",
            "",
        ]
    )


def build_report_impl_timing_tcl(
    *,
    xpr_path: Path,
    report_path: Path,
) -> str:
    """Build Tcl that regenerates post-implementation timing from ``impl_1``."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    report_dir_q = tcl_quote(_tcl_path(report_path.parent))
    report_q = tcl_quote(_tcl_path(report_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            f"open_project {xpr_q}",
            "if {[llength [get_runs -quiet impl_1]] == 0} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=not_started"',
            'puts "VIVADO_MCP_IMPL_ERROR=impl_1 run does not exist"',
            "close_project",
            "exit 1",
            "}",
            "set _mcp_run_status [get_property STATUS [get_runs impl_1]]",
            'puts "VIVADO_MCP_IMPL_RUN_STATUS=$_mcp_run_status"',
            'if {![string match -nocase "*Complete*" $_mcp_run_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_IMPL_STATUS=not_started"',
            'puts "VIVADO_MCP_IMPL_ERROR=Implementation has not completed: $_mcp_run_status"',
            "close_project",
            "exit 1",
            "}",
            f"file mkdir {report_dir_q}",
            "open_run impl_1 -name mcp_impl_design",
            "if {[catch {"
            f"report_timing_summary -delay_type min_max -max_paths 10 -file {report_q}"
            "} _mcp_tm_err]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_TIMING_STATUS=not_available"',
            'puts "VIVADO_MCP_TIMING_ERROR=$_mcp_tm_err"',
            "catch {close_design}",
            "close_project",
            "exit 1",
            "}",
            f'puts "VIVADO_MCP_IMPL_TIMING_REPORT={_tcl_path(report_path)}"',
            'puts "VIVADO_MCP_TIMING_STATUS=available"',
            "catch {close_design}",
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            "exit 0",
            "",
        ]
    )


def build_generate_bitstream_tcl(*, xpr_path: Path) -> str:
    """Build Tcl to generate a bitstream via ``impl_1 -to_step write_bitstream``.

    Requires completed ``synth_1`` and ``impl_1`` (at least through
    ``route_design``). Does not silently re-run synthesis or place-and-route
    from scratch beyond continuing the implementation run to write_bitstream.
    Targets Vivado 2018.2 project-mode batch flow.
    """
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            *_tcl_open_project_with_lock_retry(xpr_q),
            "set_property source_mgmt_mode All [current_project]",
            "update_compile_order -fileset sources_1",
            "set _mcp_top [get_property top [current_fileset]]",
            'if {$_mcp_top eq ""} {',
            "set _mcp_candidates [get_files -quiet -of_objects [get_filesets sources_1]]",
            "if {[llength $_mcp_candidates] > 0} {",
            "set _mcp_guess [file rootname [file tail [lindex $_mcp_candidates 0]]]",
            "set_property top $_mcp_guess [current_fileset]",
            "set_property top_lib xil_defaultlib [current_fileset]",
            "update_compile_order -fileset sources_1",
            "set _mcp_top [get_property top [current_fileset]]",
            "}",
            "}",
            'if {$_mcp_top eq ""} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=failed"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR=Top module is not set on sources_1"',
            "close_project",
            "exit 1",
            "}",
            'puts "VIVADO_MCP_BITSTREAM_TOP=$_mcp_top"',
            "if {[llength [get_runs -quiet synth_1]] == 0} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=blocked"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR='
            'Implementation must complete before bitstream generation"',
            "close_project",
            "exit 0",
            "}",
            "set _mcp_synth_status [get_property STATUS [get_runs synth_1]]",
            'puts "VIVADO_MCP_SYNTH_RUN_STATUS=$_mcp_synth_status"',
            'if {![string match -nocase "*Complete*" $_mcp_synth_status] || '
            '[string match -nocase "*ERROR*" $_mcp_synth_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=blocked"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR='
            'Implementation must complete before bitstream generation"',
            "close_project",
            "exit 0",
            "}",
            "if {[llength [get_runs -quiet impl_1]] == 0} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=blocked"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR='
            'Implementation must complete before bitstream generation"',
            "close_project",
            "exit 0",
            "}",
            "set _mcp_impl_status [get_property STATUS [get_runs impl_1]]",
            'puts "VIVADO_MCP_IMPL_RUN_STATUS=$_mcp_impl_status"',
            'if {[string match -nocase "*ERROR*" $_mcp_impl_status] || '
            '[string match -nocase "*fail*" $_mcp_impl_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=failed"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR='
            'Implementation failed; cannot generate bitstream: $_mcp_impl_status"',
            "close_project",
            "exit 1",
            "}",
            # Require a completed implementation step (route_design or later).
            'if {![string match -nocase "*Complete*" $_mcp_impl_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=blocked"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR='
            'Implementation must complete before bitstream generation"',
            "close_project",
            "exit 0",
            "}",
            # If write_bitstream already completed, locate .bit and exit OK.
            'if {[string match -nocase "*write_bitstream*Complete*" '
            '$_mcp_impl_status]} {',
            "set _mcp_run_dir [get_property DIRECTORY [get_runs impl_1]]",
            "set _mcp_bit [file normalize "
            "[file join $_mcp_run_dir ${_mcp_top}.bit]]",
            "if {![file exists $_mcp_bit]} {",
            "set _mcp_bits [glob -nocomplain [file join $_mcp_run_dir *.bit]]",
            "if {[llength $_mcp_bits] > 0} {",
            "set _mcp_bit [file normalize [lindex $_mcp_bits 0]]",
            "}",
            "}",
            "if {[file exists $_mcp_bit] && [file isfile $_mcp_bit] && "
            "[file size $_mcp_bit] > 0} {",
            'puts "VIVADO_MCP_BITSTREAM_PATH=$_mcp_bit"',
            'puts "VIVADO_MCP_BITSTREAM_SIZE=[file size $_mcp_bit]"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=completed"',
            'puts "VIVADO_MCP_STATUS=OK"',
            "close_project",
            "exit 0",
            "}",
            "}",
            # Continue impl_1 through write_bitstream (Vivado 2018.2 project mode).
            "if {[catch {launch_runs impl_1 -to_step write_bitstream -jobs 1} "
            "_mcp_launch_err]} {",
            "if {[catch {launch_runs impl_1 -to_step write_bitstream} "
            "_mcp_launch_err2]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=failed"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR=$_mcp_launch_err2"',
            "close_project",
            "exit 1",
            "}",
            "}",
            "wait_on_run impl_1",
            "set _mcp_impl_status [get_property STATUS [get_runs impl_1]]",
            "set _mcp_progress [get_property PROGRESS [get_runs impl_1]]",
            'puts "VIVADO_MCP_IMPL_RUN_STATUS=$_mcp_impl_status"',
            'puts "VIVADO_MCP_BITSTREAM_PROGRESS=$_mcp_progress"',
            'puts "VIVADO_MCP_IMPL_RUN=impl_1"',
            'if {[string match -nocase "*ERROR*" $_mcp_impl_status] || '
            '[string match -nocase "*fail*" $_mcp_impl_status] || '
            '![string match -nocase "*Complete*" $_mcp_impl_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=failed"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR='
            'Bitstream generation failed: $_mcp_impl_status"',
            "close_project",
            "exit 1",
            "}",
            "set _mcp_run_dir [get_property DIRECTORY [get_runs impl_1]]",
            "set _mcp_bit [file normalize "
            "[file join $_mcp_run_dir ${_mcp_top}.bit]]",
            "if {![file exists $_mcp_bit]} {",
            "set _mcp_bits [glob -nocomplain [file join $_mcp_run_dir *.bit]]",
            "if {[llength $_mcp_bits] > 0} {",
            "set _mcp_bit [file normalize [lindex $_mcp_bits 0]]",
            "}",
            "}",
            "if {![file exists $_mcp_bit] || ![file isfile $_mcp_bit]} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=failed"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR='
            'Bitstream generation finished but .bit file was not found"',
            "close_project",
            "exit 1",
            "}",
            "set _mcp_bit_size [file size $_mcp_bit]",
            "if {$_mcp_bit_size <= 0} {",
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=failed"',
            'puts "VIVADO_MCP_BITSTREAM_PATH=$_mcp_bit"',
            'puts "VIVADO_MCP_BITSTREAM_SIZE=0"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR='
            'Generated bitstream file is empty (0 bytes)"',
            "close_project",
            "exit 1",
            "}",
            # Prefer write_bitstream Complete!; also accept Complete + valid .bit.
            'if {![string match -nocase "*write_bitstream*Complete*" '
            '$_mcp_impl_status] && '
            '![string match -nocase "*Complete*" $_mcp_impl_status]} {',
            'puts "VIVADO_MCP_STATUS=ERROR"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=failed"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR='
            'write_bitstream did not complete: $_mcp_impl_status"',
            "close_project",
            "exit 1",
            "}",
            'puts "VIVADO_MCP_BITSTREAM_PATH=$_mcp_bit"',
            'puts "VIVADO_MCP_BITSTREAM_SIZE=$_mcp_bit_size"',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=completed"',
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            "exit 0",
            "",
        ]
    )


def build_bitstream_status_tcl(*, xpr_path: Path) -> str:
    """Build Tcl that reports bitstream / impl_1 STATUS without launching."""
    xpr_q = tcl_quote(_tcl_path(xpr_path))
    return "\n".join(
        [
            "# Generated by vivado-mcp — do not edit",
            *_tcl_open_project_with_lock_retry(xpr_q),
            "set _mcp_top [get_property top [current_fileset]]",
            'puts "VIVADO_MCP_BITSTREAM_TOP=$_mcp_top"',
            "if {[llength [get_runs -quiet synth_1]] == 0} {",
            'puts "VIVADO_MCP_SYNTH_STATUS=not_started"',
            "} else {",
            "set _mcp_synth_status [get_property STATUS [get_runs synth_1]]",
            'puts "VIVADO_MCP_SYNTH_RUN_STATUS=$_mcp_synth_status"',
            "}",
            "if {[llength [get_runs -quiet impl_1]] == 0} {",
            'puts "VIVADO_MCP_IMPL_STATUS=not_started"',
            'puts "VIVADO_MCP_IMPL_RUN_STATUS="',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=blocked"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR=Implementation has not completed"',
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            "exit 0",
            "}",
            "set _mcp_impl_status [get_property STATUS [get_runs impl_1]]",
            "set _mcp_progress [get_property PROGRESS [get_runs impl_1]]",
            'puts "VIVADO_MCP_IMPL_RUN=impl_1"',
            'puts "VIVADO_MCP_IMPL_RUN_STATUS=$_mcp_impl_status"',
            'puts "VIVADO_MCP_BITSTREAM_PROGRESS=$_mcp_progress"',
            'if {[string match -nocase "*ERROR*" $_mcp_impl_status] || '
            '[string match -nocase "*fail*" $_mcp_impl_status]} {',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=failed"',
            '} elseif {[string match -nocase "*write_bitstream*Complete*" '
            '$_mcp_impl_status]} {',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=completed"',
            '} elseif {[string match -nocase "*write_bitstream*" '
            '$_mcp_impl_status] && '
            '([string match -nocase "*Running*" $_mcp_impl_status] || '
            '[string match -nocase "*Queued*" $_mcp_impl_status])} {',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=running"',
            '} elseif {[string match -nocase "*cancel*" $_mcp_impl_status]} {',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=cancelled"',
            '} elseif {![string match -nocase "*Complete*" $_mcp_impl_status]} {',
            'puts "VIVADO_MCP_BITSTREAM_STATUS=blocked"',
            'puts "VIVADO_MCP_BITSTREAM_ERROR=Implementation has not completed"',
            "} else {",
            # route_design Complete! (or similar) — impl done, bitstream not started
            'puts "VIVADO_MCP_BITSTREAM_STATUS=not_started"',
            "}",
            "set _mcp_run_dir [get_property DIRECTORY [get_runs impl_1]]",
            'if {$_mcp_top ne ""} {',
            "set _mcp_bit [file normalize "
            "[file join $_mcp_run_dir ${_mcp_top}.bit]]",
            "} else {",
            'set _mcp_bit ""',
            "}",
            'if {$_mcp_bit eq "" || ![file exists $_mcp_bit]} {',
            "set _mcp_bits [glob -nocomplain [file join $_mcp_run_dir *.bit]]",
            "if {[llength $_mcp_bits] > 0} {",
            "set _mcp_bit [file normalize [lindex $_mcp_bits 0]]",
            "}",
            "}",
            'if {$_mcp_bit ne "" && [file exists $_mcp_bit] && '
            "[file isfile $_mcp_bit]} {",
            'puts "VIVADO_MCP_BITSTREAM_PATH=$_mcp_bit"',
            'puts "VIVADO_MCP_BITSTREAM_SIZE=[file size $_mcp_bit]"',
            "}",
            "close_project",
            'puts "VIVADO_MCP_STATUS=OK"',
            "exit 0",
            "",
        ]
    )


def _tcl_path(path: Path) -> str:
    """Return a path string suitable for Tcl on Windows and Linux.

    Vivado on Windows accepts forward slashes. Always normalize separators so
    Windows-style paths remain safe even when this code runs on Linux (for
    example in CI while generating Tcl for a remote Windows Vivado).
    """
    return str(path.expanduser()).replace("\\", "/")


def _tcl_open_project_with_lock_retry(xpr_q: str) -> list[str]:
    """Tcl lines that open a project, clearing a stale ``.lck`` and retrying.

    Vivado batch runs on Windows occasionally leave ``*.xpr.lck`` behind when a
    previous process exits non-zero. A single retry after deleting the lock
    makes open/close flows much more reliable in integration tests.
    """
    return [
        f"set _mcp_xpr {xpr_q}",
        "set _mcp_lck ${_mcp_xpr}.lck",
        "if {[file exists $_mcp_lck]} {",
        "catch {file delete -force $_mcp_lck}",
        "}",
        "if {[catch {open_project $_mcp_xpr} _mcp_open_err]} {",
        "after 1500",
        "if {[file exists $_mcp_lck]} {",
        "catch {file delete -force $_mcp_lck}",
        "}",
        "if {[catch {open_project $_mcp_xpr} _mcp_open_err2]} {",
        'puts "VIVADO_MCP_STATUS=ERROR"',
        'puts "VIVADO_MCP_ERROR=Could not open project: $_mcp_open_err2"',
        "exit 1",
        "}",
        "}",
    ]